apiVersion: v1
kind: Pod
metadata:
  name: container-env-example
spec:
  containers:
    - name: my-container
      image: busybox
      args: ['tail', '-f', '/dev/null']
      envFrom:
        - configMapRef:
            name: log-level-configmap
        - configMapRef:
            name: start-k8s
      env:
        - name: ENV_KEYNAME_1
          valueFrom:
            configMapKeyRef:
              name: log-level-configmap
              key: LOG_LEVEL
        - name: ENV_KEYNAME_2
          valueFrom:
            configMapKeyRef:
              name: start-k8s
              key: k8s
